const express = require('express')
const RestaurantR = express.Router()
const UserController = require('../Controllers/UserController')
const RestaurantController = require('../Controllers/RestaurantController')
const upload = require('../middlewares/multer')
const MenuRoute = require('./MenuRoute')
RestaurantR.use('/:restId/Menu',MenuRoute)
RestaurantR.route('/getrestaurant').get(RestaurantController.findrestaurant)
RestaurantR.route('/createRestaurant').post(UserController.protected,RestaurantController.createRestaurant)
RestaurantR.route('/getaRestaurant/:id').get(RestaurantController.getRestaurant)
RestaurantR.route('/verifyrestaurant/:id').get(UserController.protected,UserController.restricatedTo('admin'),RestaurantController.verfiyRestaurant)
RestaurantR.route('/getMyRestaurant').get(UserController.protected,RestaurantController.getMyrestaurant)
RestaurantR.route('/updateRestaurant/:id').patch(UserController.protected,RestaurantController.updateRestaurant)
RestaurantR.route('/uploadCoverPhoto/:id').patch(UserController.protected,upload,RestaurantController.uploadcoverphoto)
RestaurantR.route('/deleterestaurant/:id').delete(UserController.protected,RestaurantController.deleteRestaurant)
module.exports = RestaurantR